### ISSUE TITLE
its still boring

### ISSUE THREAD

**Issue by nta** [Xinerki/Story#2]
issue #1 didn't get fixed i believe though i didn't play yet

**Comment by Xinerki** [comment]
lol

**Comment by nta** [comment]
hey don't close my issue on me!!!

**Comment by Xinerki** [comment]
ill close it behind you

**Comment by nta** [comment]
that was the door, not the issue.

**Comment by nta** [comment]
didn't get less boring, fix it please :(

**Comment by Xinerki** [comment]
it did get less boring, you can _play with **another player**_ :OOOOOOOO

**Comment by nta** [comment]
make new issue: 'people are boring'

assign @dkluin to it

**Comment by Xinerki** [comment]
@dkluin is so boring he is not assignable to such issue on this project
